# Generated by Django 5.2.1 on 2025-07-12 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='car_images/')),
                ('mileage', models.PositiveIntegerField(help_text='Kilometraza')),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('LPG', 'LPG')], max_length=10)),
                ('car_type', models.CharField(choices=[('COUPE', 'Kupe'), ('SEDAN', 'Limuzina'), ('HATCHBACK', 'Hečbek'), ('SUV', 'SUV'), ('CONVERTIBLE', 'Kabriolet'), ('WAGON', 'Karavan'), ('PICKUP', 'Pickup')], max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
