# Generated by Django 5.2.1 on 2025-07-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, help_text='Kratak opis automobila (opciono)', max_length=1000),
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
