# Generated by Django 5.2.1 on 2025-07-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_displacement',
            field=models.PositiveIntegerField(default=1600, help_text='Engine displacement in cubic centimeters (e.g. 1600)'),
            preserve_default=False,
        ),
    ]
